// Package httpapi wires HTTP routes to their handlers.
package httpapi

import (
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"

	_ "github.com/MGeovany/rivalo-server/docs" // OpenAPI spec generated by swag

	"github.com/MGeovany/rivalo-server/internal/auth"
	"github.com/MGeovany/rivalo-server/internal/logger"
	"github.com/MGeovany/rivalo-server/internal/pitch"
	"github.com/MGeovany/rivalo-server/internal/profile"
	"github.com/MGeovany/rivalo-server/internal/session"
)

// Deps holds the dependencies the HTTP handlers need. DB, Profiles, Sessions and
// Pitches may be nil in environments without a configured database; in that case
// /health reports the database as disabled and the data endpoints return 503.
type Deps struct {
	DB       Pinger
	Profiles profile.Store
	Sessions session.Store
	Pitches  pitch.Store
	Verifier auth.Verifier
}

// NewRouter builds the HTTP handler for the API.
func NewRouter(d Deps) http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /health", healthHandler(d.DB))

	mux.HandleFunc("GET /v1/me", d.requireAuth(d.handleGetMe))
	mux.HandleFunc("PUT /v1/me", d.requireAuth(d.handleUpdateMe))

	mux.HandleFunc("POST /v1/pitches", d.requireAuth(d.handleCreatePitch))
	mux.HandleFunc("GET /v1/pitches", d.requireAuth(d.handleListPitches))
	mux.HandleFunc("GET /v1/pitches/{id}", d.requireAuth(d.handleGetPitch))
	mux.HandleFunc("PUT /v1/pitches/{id}", d.requireAuth(d.handleUpdatePitch))
	mux.HandleFunc("DELETE /v1/pitches/{id}", d.requireAuth(d.handleDeletePitch))

	mux.HandleFunc("POST /v1/sessions", d.requireAuth(d.handleCreateSession))
	mux.HandleFunc("GET /v1/sessions", d.requireAuth(d.handleListSessions))
	mux.HandleFunc("GET /v1/sessions/{id}", d.requireAuth(d.handleGetSession))
	mux.HandleFunc("PUT /v1/sessions/{id}", d.requireAuth(d.handleUpdateSession))
	mux.HandleFunc("PATCH /v1/sessions/{id}", d.requireAuth(d.handlePatchSessionContext))
	mux.HandleFunc("DELETE /v1/sessions/{id}", d.requireAuth(d.handleDeleteSession))

	mux.Handle("/docs/", httpSwagger.Handler(httpSwagger.URL("/docs/doc.json")))
	mux.HandleFunc("GET /docs", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/docs/index.html", http.StatusTemporaryRedirect)
	})

	return logger.RequestLog(mux)
}
